webtalk_init -webtalk_dir /u/satrajit/PRODUCTS/FPGA/XILINX/github/08-24/check/XilinxTclStore/tclapp/atrenta/spyglass/test/vivado_proj_1/vfifo_controller_base_x4_gen2.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Sep 24 11:38:54 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1215546" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "531_2343_1430158964_680" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "94974b2d-b461-405d-8a23-1f7ffffb2f89" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3619e09b-065d-47d0-ac85-eae3ece9d4d9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseServer" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Server release 5.8 (Tikanga)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           E5630  @ 2.53GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2527.066 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 1408166507 -regid "531_2343_1430158964_680" -xml /u/satrajit/PRODUCTS/FPGA/XILINX/github/08-24/check/XilinxTclStore/tclapp/atrenta/spyglass/test/vivado_proj_1/vfifo_controller_base_x4_gen2.hw/webtalk/usage_statistics_ext_labtool.xml -html /u/satrajit/PRODUCTS/FPGA/XILINX/github/08-24/check/XilinxTclStore/tclapp/atrenta/spyglass/test/vivado_proj_1/vfifo_controller_base_x4_gen2.hw/webtalk/usage_statistics_ext_labtool.html -wdm /u/satrajit/PRODUCTS/FPGA/XILINX/github/08-24/check/XilinxTclStore/tclapp/atrenta/spyglass/test/vivado_proj_1/vfifo_controller_base_x4_gen2.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
