# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {
  C:/Users/nikc/Desktop/jenkins/src/ff_ce_sync_rst.v
  C:/Users/nikc/Desktop/jenkins/src/ff_replicator.v
}
read_xdc C:/Users/nikc/Desktop/jenkins/src/ff_replicator.xdc
set_property used_in_implementation false [get_files C:/Users/nikc/Desktop/jenkins/src/ff_replicator.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/nikc/Desktop/jenkins/project_hook_high/workspace/tp/tp.data/wt [current_project]
set_property parent.project_dir C:/Users/nikc/Desktop/jenkins/project_hook_high/workspace/tp [current_project]
synth_design -top ff_replicator -part xc7vx485tffg1157-1
write_checkpoint ff_replicator.dcp
report_utilization -file ff_replicator_utilization_synth.rpt -pb ff_replicator_utilization_synth.pb
set src_rc [catch { 
  puts "source C:/Users/nikc/Desktop/jenkins/project_hook_high/hook_synth.tcl"
  source C:/Users/nikc/Desktop/jenkins/project_hook_high/hook_synth.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 error "$_RESULT"
  send_msg_id runtcl-2 error "sourcing script C:/Users/nikc/Desktop/jenkins/project_hook_high/hook_synth.tcl failed"
  return -code error
}
