####################################################################################################
# HEADER_BEGIN
# COPYRIGHT NOTICE
# Copyright 2001-2013 Xilinx Inc. All Rights Reserved.
# http://www.xilinx.com/support
# HEADER_END
####################################################################################################
package require Vivado 2013.1

namespace eval ::tclapp::xilinx::designutils {
    namespace export isLineComment
}

proc ::tclapp::xilinx::designutils::isLineComment {line} {
    # Summary : figure whether a line is a tcl comment or not

    # Argument Usage:
    # line : string to be tested
    
    # Return Value:
    # returns 1 if argument line is comment, 0 otherwise.
    
    # TODO - speedup - combine these into a single regexp call
    if {[regexp {^\s*$} $line]} {
        # line is all whitespace or empty, so assume comment
        return 1
    } elseif {[regexp {^,+$} $line]} {
        # line contains only commas, so assume comment
        return 1
    } elseif {![regexp {,} $line]} {
        # line does not contain any commas, so assume comment
        return 1
    } elseif {[regexp {^Top:} $line]} {
        # line contains known csv header comment "Top:"
        return 1
    } elseif {[regexp {^Netlist:} $line]} {
        # line contains known csv header comment "Netlist:"
        return 1
    } elseif {[regexp {^Generated by:} $line]} {
        # line contains known csv header comment "Generated by:"
        return 1
    } elseif {[regexp {^Build:} $line]} {
        # line contains known csv header comment "Build:"
        return 1
    } else {
        return 0
    }
}
####################################################################################################
# HEADER_BEGIN
# COPYRIGHT NOTICE
# Copyright 2001-2013 Xilinx Inc. All Rights Reserved.
# http://www.xilinx.com/support
# HEADER_END
####################################################################################################
